repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ["--"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args: ["--config-file", "mypy.ini", "-p", "releasecopilot"]
        pass_filenames: false
        additional_dependencies:
          - types-PyYAML==6.0.12.20240808
          - types-requests==2.32.0.20241016
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.1.0
        types_or: [yaml]
  - repo: local
    hooks:
      - id: check-generated-wave
        name: Check generated wave artifacts
        entry: make check-generated
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
        args: ["--"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: end-of-file-fixer
        args: ["--"]
        types_or: [python, yaml, json, toml]
      - id: trailing-whitespace
        args: ["--markdown-linebreak-ext=md,markdown", "--"]
        types_or: [python, yaml, json, toml]
