default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - "--config-file"
          - "pyproject.toml"
        pass_filenames: false
        additional_dependencies:
          - types-PyYAML==6.0.12.20240808
          - types-requests==2.32.0.20241016
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args:
          - "--ignore-words-list=crate,te,ser"
          - "--"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        args: ["--"]
      - id: trailing-whitespace
        args: ["--"]
      - id: detect-private-key
        args: ["--"]
  - repo: local
    hooks:
      - id: check-generated-wave
        name: Check generated wave artifacts
        entry: python tools/hooks/check_generator_drift.py
        language: system
        pass_filenames: false
ci:
  autofix_prs: true
  autofix_commit_msg: "chore(pre-commit): auto fixes from pre-commit.ci"
  autoupdate_schedule: monthly
