[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E4", "F404", "I", "F"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["releasecopilot"]
combine-as-imports = true
force-sort-within-sections = true
