[tool.ruff]
line-length = 100
target-version = "py310"
src = ["src", "."]

[tool.ruff.lint]
select = ["E4", "F"]
extend-select = ["I"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = [
    "releasecopilot",
    "cli",
    "clients",
    "config",
    "export",
    "matcher",
    "ops",
    "processors",
    "services",
    "tracking",
    "ui",
]
combine-as-imports = true
force-sort-within-sections = true

[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 100
target-version = ["py310"]

[tool.mypy]
python_version = "3.11"
mypy_path = ["src"]
explicit_package_bases = true
namespace_packages = true
ignore_missing_imports = true
follow_imports = "silent"
warn_unused_configs = true
warn_redundant_casts = true
show_error_codes = true
files = ["src", "tests"]

[[tool.mypy.overrides]]
module = "rag_aws.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "services.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true

[tool.pytest.ini_options]
addopts = "-q --cov=src --cov-report=xml --cov-report=json"
markers = [
    "integration: integration-level recovery tool tests",
    "network: tests that require live network access",
]
pythonpath = ["src", "."]
testpaths = ["tests"]
tmp_path_retention_count = 3
tmp_path_retention_policy = "failed"

[tool.coverage.run]
source = ["src"]
branch = true

[tool.coverage.report]
omit = [
    "infra/**",
    "scripts/**",
    "tools/**",
    "services/**/handler.py",  # if not exercised in unit tests
    "src/**/__main__.py",
]
fail_under = 70
