[tool.ruff]
line-length = 100
target-version = "py311"
src = ["src", "."]

[tool.ruff.lint]
select = ["E4", "F", "I"]
ignore = []
fixable = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = [
    "releasecopilot",
    "cli",
    "clients",
    "config",
    "export",
    "matcher",
    "ops",
    "processors",
    "services",
    "tracking",
    "ui",
]
combine-as-imports = true
force-sort-within-sections = true
