name: cdk-ci

on:
  pull_request:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

jobs:
  synth-diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install CDK CLI
        run: npm install -g aws-cdk@2
      - name: Install dependencies
        run: pip install -r cdk/requirements.txt
      - name: CDK synth
        working-directory: cdk
        run: cdk synth
      - name: CDK diff
        working-directory: cdk
        run: cdk diff || true
