name: cdk-ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'cdk/**'
      - 'cdk.json'
      - 'package*.json'
      - 'requirements*.txt'
      - '.github/workflows/cdk-ci.yml'
  workflow_dispatch:

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CDK & Python dependencies
        run: |
          npm install -g aws-cdk
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
          if [ -f infra/cdk/requirements.txt ]; then python -m pip install -r infra/cdk/requirements.txt; fi

      - name: Verify CDK root layout
        run: ./scripts/ci/verify_cdk_root_layout.sh

      - name: CDK List
        run: npx cdk list

      - name: CDK Synth
        run: npx cdk synth

      - name: Configure AWS credentials
        if: vars.OIDC_ROLE_ARN != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          role-session-name: cdk-deploy-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Diff
        run: npx cdk diff

      - name: CDK Deploy
        if: >-
          vars.OIDC_ROLE_ARN != '' &&
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: npx cdk deploy --require-approval never
