name: cdk-ci

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
    paths:
      - 'infra/**'
      - 'cdk/**'
      - 'cdk.json'
      - 'package*.json'
      - 'requirements*.txt'
      - '.github/workflows/cdk-ci.yml'
  workflow_dispatch:

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-west-2
      NPX_YES: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20.x)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Python (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install CDK & Python deps
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}"
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -r infra/cdk/requirements.txt
          npm install -g aws-cdk

      - name: CDK List
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}"
          source .venv/bin/activate
          npx --yes cdk list

      - name: CDK Synth
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}"
          source .venv/bin/activate
          npx --yes cdk synth

      - name: Configure AWS credentials
        if: vars.OIDC_ROLE_ARN != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.OIDC_ROLE_ARN }}
          role-session-name: cdk-deploy-${{ github.run_id }}
          aws-region: ${{ env.AWS_REGION }}

      - name: CDK Diff
        if: vars.OIDC_ROLE_ARN != ''
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}"
          source .venv/bin/activate
          npx --yes cdk diff

      - name: CDK Deploy
        if: >-
          vars.OIDC_ROLE_ARN != '' &&
          github.event_name == 'push' &&
          (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        run: |
          set -euo pipefail
          cd "${GITHUB_WORKSPACE}"
          source .venv/bin/activate
          npx --yes cdk deploy --require-approval never
