name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry==1.8.3
          poetry --version

      - name: Install deps from lock
        run: poetry install --no-interaction --no-ansi

      - name: Validate lockfile
        run: poetry lock --check

      - name: Ruff (lint)
        run: poetry run ruff check .

      - name: Ruff (format check)
        run: poetry run ruff format --check .

      - name: Pre-commit (hooks)
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/rag-aws
        run: poetry run pre-commit run --all-files

      - name: Mypy (typecheck)
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/rag-aws
        run: poetry run mypy .

      - name: Pytest (coverage ≥ 70%)
        env:
          PYTHONPATH: ${{ github.workspace }}:${{ github.workspace }}/rag-aws
        run: |
          poetry run pytest
