name: CI
on:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"

      - name: Install Poetry
        run: |
          pipx install poetry==1.8.3
          poetry --version

      - name: Configure Poetry (no venv in-project)
        run: poetry config virtualenvs.create true

      - name: Install deps from lock
        run: poetry install --no-interaction --no-ansi --sync

      - name: Ruff (lint)
        run: poetry run ruff check .

      - name: Ruff (format check)
        run: poetry run ruff format --check .

      - name: Mypy (typecheck)
        run: poetry run mypy .

      - name: Pytest (coverage ≥ 70%)
        run: |
          poetry run pytest -q
